// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';
import {svc} from '../models';

export function ConfigMode():Promise<string>;

export function ConfigText():Promise<string>;

export function GetStatus():Promise<ipc.Status>;

export function Preflight():Promise<Array<svc.Check>>;

export function ServiceInstall():Promise<void>;

export function ServiceStart():Promise<void>;

export function ServiceState():Promise<string>;

export function ServiceStop():Promise<void>;

export function SetConfigMode(arg1:string):Promise<void>;

export function SocketPath():Promise<string>;

export function Version():Promise<string>;
