// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigMode() {
  return window['go']['main']['App']['ConfigMode']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ServiceInstall() {
  return window['go']['main']['App']['ServiceInstall']();
}

export function ServiceStart() {
  return window['go']['main']['App']['ServiceStart']();
}

export function ServiceState() {
  return window['go']['main']['App']['ServiceState']();
}

export function ServiceStop() {
  return window['go']['main']['App']['ServiceStop']();
}

export function SetConfigMode(arg1) {
  return window['go']['main']['App']['SetConfigMode'](arg1);
}

export function SocketPath() {
  return window['go']['main']['App']['SocketPath']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
